/* eslint-disable */
// Generated by scripts/buildCareerStockData.mjs
// Do not edit by hand unless the generator script changes.

export type CareerStockPoint = {
  date: string;
  close: number;
};

export type CareerStockMetrics = {
  startShares: number;
  endShares: number;
  startMarketCap: number;
  endMarketCap: number;
  priceDelta: number;
  priceDeltaPct: number;
  marketCapDelta: number;
  marketCapDeltaPct: number;
};

export type CareerStockCompanySnapshot = {
  id: string;
  company: string;
  ticker: string;
  tenureLabel: string;
  isLive: boolean;
  startPoint: CareerStockPoint;
  endPoint: CareerStockPoint;
  points: CareerStockPoint[];
  metrics: CareerStockMetrics;
};

export const CAREER_STOCK_SNAPSHOT_GENERATED_AT = "2026-05-26";

export const careerStockSnapshot: CareerStockCompanySnapshot[] = [
  {
    "id": "amd",
    "company": "Advanced Micro Devices (AMD)",
    "ticker": "AMD",
    "tenureLabel": "MAY 2023 - AUG 2024",
    "isLive": false,
    "startPoint": {
      "date": "2023-05-01",
      "close": 89.69000244140625
    },
    "endPoint": {
      "date": "2024-08-30",
      "close": 148.55999755859375
    },
    "points": [
      {
        "date": "2023-05-01",
        "close": 89.69000244140625
      },
      {
        "date": "2023-05-15",
        "close": 97.4000015258789
      },
      {
        "date": "2023-05-30",
        "close": 125.2699966430664
      },
      {
        "date": "2023-06-14",
        "close": 127.33000183105469
      },
      {
        "date": "2023-06-29",
        "close": 111.23999786376953
      },
      {
        "date": "2023-07-14",
        "close": 115.94000244140625
      },
      {
        "date": "2023-07-28",
        "close": 112.95999908447266
      },
      {
        "date": "2023-08-11",
        "close": 107.56999969482422
      },
      {
        "date": "2023-08-25",
        "close": 102.25
      },
      {
        "date": "2023-09-12",
        "close": 105.30999755859375
      },
      {
        "date": "2023-09-26",
        "close": 95.95999908447266
      },
      {
        "date": "2023-10-10",
        "close": 109.01000213623047
      },
      {
        "date": "2023-10-24",
        "close": 101.66999816894531
      },
      {
        "date": "2023-11-07",
        "close": 113.44999694824219
      },
      {
        "date": "2023-11-22",
        "close": 122.51000213623047
      },
      {
        "date": "2023-12-07",
        "close": 128.3699951171875
      },
      {
        "date": "2023-12-21",
        "close": 139.91000366210938
      },
      {
        "date": "2024-01-08",
        "close": 146.17999267578125
      },
      {
        "date": "2024-01-23",
        "close": 168.4199981689453
      },
      {
        "date": "2024-02-06",
        "close": 167.8800048828125
      },
      {
        "date": "2024-02-22",
        "close": 181.86000061035156
      },
      {
        "date": "2024-03-07",
        "close": 211.3800048828125
      },
      {
        "date": "2024-03-21",
        "close": 178.67999267578125
      },
      {
        "date": "2024-04-05",
        "close": 170.4199981689453
      },
      {
        "date": "2024-04-19",
        "close": 146.63999938964844
      },
      {
        "date": "2024-05-06",
        "close": 155.77999877929688
      },
      {
        "date": "2024-05-20",
        "close": 166.3300018310547
      },
      {
        "date": "2024-06-04",
        "close": 159.99000549316406
      },
      {
        "date": "2024-06-18",
        "close": 154.6300048828125
      },
      {
        "date": "2024-07-03",
        "close": 163.89999389648438
      },
      {
        "date": "2024-07-18",
        "close": 155.77000427246094
      },
      {
        "date": "2024-08-02",
        "close": 132.5
      },
      {
        "date": "2024-08-16",
        "close": 148.55999755859375
      },
      {
        "date": "2024-08-30",
        "close": 148.55999755859375
      }
    ],
    "metrics": {
      "startShares": 1610361870,
      "endShares": 1618481845,
      "startMarketCap": 144433360051.84753,
      "endMarketCap": 240441658941.8283,
      "priceDelta": 58.8699951171875,
      "priceDeltaPct": 65.63718755125109,
      "marketCapDelta": 96008298889.98077,
      "marketCapDeltaPct": 66.4723848115951
    }
  },
  {
    "id": "amd-present",
    "company": "Advanced Micro Devices (AMD)",
    "ticker": "AMD",
    "tenureLabel": "JUL 2025 - PRESENT",
    "isLive": true,
    "startPoint": {
      "date": "2025-07-01",
      "close": 136.11000061035156
    },
    "endPoint": {
      "date": "2026-05-22",
      "close": 467.510009765625
    },
    "points": [
      {
        "date": "2025-07-01",
        "close": 136.11000061035156
      },
      {
        "date": "2025-07-11",
        "close": 146.4199981689453
      },
      {
        "date": "2025-07-22",
        "close": 154.72000122070312
      },
      {
        "date": "2025-07-30",
        "close": 179.50999450683594
      },
      {
        "date": "2025-08-08",
        "close": 172.75999450683594
      },
      {
        "date": "2025-08-19",
        "close": 166.5500030517578
      },
      {
        "date": "2025-08-28",
        "close": 168.5800018310547
      },
      {
        "date": "2025-09-09",
        "close": 155.82000732421875
      },
      {
        "date": "2025-09-18",
        "close": 157.9199981689453
      },
      {
        "date": "2025-09-26",
        "close": 159.4600067138672
      },
      {
        "date": "2025-10-07",
        "close": 211.50999450683594
      },
      {
        "date": "2025-10-16",
        "close": 234.55999755859375
      },
      {
        "date": "2025-10-27",
        "close": 259.6700134277344
      },
      {
        "date": "2025-11-05",
        "close": 256.3299865722656
      },
      {
        "date": "2025-11-13",
        "close": 247.9600067138672
      },
      {
        "date": "2025-11-24",
        "close": 215.0500030517578
      },
      {
        "date": "2025-12-04",
        "close": 215.97999572753906
      },
      {
        "date": "2025-12-15",
        "close": 207.5800018310547
      },
      {
        "date": "2025-12-24",
        "close": 215.0399932861328
      },
      {
        "date": "2026-01-06",
        "close": 214.35000610351562
      },
      {
        "date": "2026-01-14",
        "close": 223.60000610351562
      },
      {
        "date": "2026-01-26",
        "close": 251.30999755859375
      },
      {
        "date": "2026-02-04",
        "close": 200.19000244140625
      },
      {
        "date": "2026-02-13",
        "close": 207.32000732421875
      },
      {
        "date": "2026-02-25",
        "close": 210.86000061035156
      },
      {
        "date": "2026-03-05",
        "close": 199.4499969482422
      },
      {
        "date": "2026-03-16",
        "close": 196.5800018310547
      },
      {
        "date": "2026-03-25",
        "close": 220.27000427246094
      },
      {
        "date": "2026-04-06",
        "close": 220.17999267578125
      },
      {
        "date": "2026-04-15",
        "close": 258.1199951171875
      },
      {
        "date": "2026-04-24",
        "close": 347.80999755859375
      },
      {
        "date": "2026-05-04",
        "close": 341.5400085449219
      },
      {
        "date": "2026-05-13",
        "close": 445.5
      },
      {
        "date": "2026-05-22",
        "close": 467.510009765625
      }
    ],
    "metrics": {
      "startShares": 1621404195,
      "endShares": 1630600639,
      "startMarketCap": 220689325971.0766,
      "endMarketCap": 762322120662.7244,
      "priceDelta": 331.40000915527344,
      "priceDeltaPct": 243.479544243033,
      "marketCapDelta": 541632794691.64777,
      "marketCapDeltaPct": 245.42772619761132
    }
  },
  {
    "id": "grmn",
    "company": "Garmin Ltd.",
    "ticker": "GRMN",
    "tenureLabel": "JAN 2022 - DEC 2022",
    "isLive": false,
    "startPoint": {
      "date": "2022-01-03",
      "close": 133.5500030517578
    },
    "endPoint": {
      "date": "2022-12-30",
      "close": 92.29000091552734
    },
    "points": [
      {
        "date": "2022-01-03",
        "close": 133.5500030517578
      },
      {
        "date": "2022-01-13",
        "close": 132.14999389648438
      },
      {
        "date": "2022-01-25",
        "close": 121.37000274658203
      },
      {
        "date": "2022-02-04",
        "close": 124.76000213623047
      },
      {
        "date": "2022-02-15",
        "close": 119.87999725341797
      },
      {
        "date": "2022-02-28",
        "close": 110.44000244140625
      },
      {
        "date": "2022-03-09",
        "close": 110.72000122070312
      },
      {
        "date": "2022-03-21",
        "close": 116.69999694824219
      },
      {
        "date": "2022-03-31",
        "close": 118.61000061035156
      },
      {
        "date": "2022-04-11",
        "close": 111.73999786376953
      },
      {
        "date": "2022-04-22",
        "close": 110.5
      },
      {
        "date": "2022-05-03",
        "close": 111.79000091552734
      },
      {
        "date": "2022-05-13",
        "close": 101.36000061035156
      },
      {
        "date": "2022-05-24",
        "close": 98.94000244140625
      },
      {
        "date": "2022-06-06",
        "close": 104.61000061035156
      },
      {
        "date": "2022-06-16",
        "close": 92.77999877929688
      },
      {
        "date": "2022-06-28",
        "close": 98.18000030517578
      },
      {
        "date": "2022-07-11",
        "close": 100.5999984741211
      },
      {
        "date": "2022-07-20",
        "close": 106.22000122070312
      },
      {
        "date": "2022-08-01",
        "close": 98.2699966430664
      },
      {
        "date": "2022-08-11",
        "close": 98.66999816894531
      },
      {
        "date": "2022-08-22",
        "close": 94.30000305175781
      },
      {
        "date": "2022-09-01",
        "close": 89.4000015258789
      },
      {
        "date": "2022-09-13",
        "close": 88.80000305175781
      },
      {
        "date": "2022-09-23",
        "close": 82.7699966430664
      },
      {
        "date": "2022-10-04",
        "close": 83.5
      },
      {
        "date": "2022-10-14",
        "close": 79.44000244140625
      },
      {
        "date": "2022-10-26",
        "close": 84.91999816894531
      },
      {
        "date": "2022-11-04",
        "close": 86.52999877929688
      },
      {
        "date": "2022-11-16",
        "close": 90.3499984741211
      },
      {
        "date": "2022-11-28",
        "close": 89.66999816894531
      },
      {
        "date": "2022-12-08",
        "close": 95.61000061035156
      },
      {
        "date": "2022-12-19",
        "close": 90.30000305175781
      },
      {
        "date": "2022-12-30",
        "close": 92.29000091552734
      }
    ],
    "metrics": {
      "startShares": 192322049,
      "endShares": 191663933,
      "startMarketCap": 25684610230.870316,
      "endMarketCap": 17688664552.04357,
      "priceDelta": -41.26000213623047,
      "priceDeltaPct": -30.89479685016555,
      "marketCapDelta": -7995945678.826744,
      "marketCapDeltaPct": -31.131271243573018
    }
  }
];
